### ISSUE TITLE
Potentially allow the use of nerd fonts.

### ISSUE THREAD

**Issue by sweetbbak** [Alex4386/decky-terminal#1]
First off I want to say that this plugin is awesome, I've been using it a lot since it came out. I'm wondering if it would be possible to support a custom font or maybe some basic nerd-font symbols.

**Comment by Alex4386** [comment]
Currently on the roadmap. Thanks for creating an issue for this.
Personally I am using Powerlevel10k on my personal machine, so It is also crucial for me.
I am currently planning to make users possible to import other css files into the terminal section so you can use any font whatever you want.

**Comment by Alex4386** [comment]
A stub Setting page has been implemented on f730bed579e7eab5e128d15ca1414c660806aa48.  

The following is required to implement:  
* [x] Implement config storage (also needed for #4)
* [x] Implement stub `<TextField>` Element for inputting custom font names
* [x] Preferably add feature to control font size
* [x] Implement frontend config loading mechanism and applying on xterm.js instance.

**Comment by Alex4386** [comment]
I haven't tested with Nerd fonts yet, but It will probably work. Will test later on and close issue if tested and after it is released as 0.2.0

**Comment by sweetbbak** [comment]
So awesome! Thank you for your work.

**Comment by Alex4386** [comment]
![image](https://github.com/Alex4386/decky-terminal/assets/27724108/fca43e11-1b8b-498c-9b1b-8020474699da)

Nerd Font has been tested and works!

![image](https://github.com/Alex4386/decky-terminal/assets/27724108/f8ae15a0-09b8-4325-b027-ff7ef4b5b01b)

**Comment by Alex4386** [comment]
Will close this issue when SteamDeckHomebrew/decky-plugin-database#426 gets merged.
